const express = require('express');
const router = express.Router();
const multer = require('multer');
const { CloudinaryStorage } = require('multer-storage-cloudinary');
const cloudinary = require('cloudinary').v2;
const Student = require('../models/Student');

// @route GET /api/health
// @desc Health check for cron-job pinging
router.get('/health', (req, res) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString(), uptime: process.uptime() });
});

// Configure Cloudinary
cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET,
});

// Configure Multer Storage with Cloudinary
const storage = new CloudinaryStorage({
    cloudinary: cloudinary,
    params: {
        folder: 'hackathon_payments',
        allowed_formats: ['jpg', 'png', 'jpeg'],
    },
});

const upload = multer({
    storage: storage,
    limits: { fileSize: 5 * 1024 * 1024 } // 5MB limit
});

// @route POST /api/verify
// @desc Verify student using email and uniqueCode
router.post('/verify', async (req, res) => {
    console.log('--- VERIFY REQUEST RECEIVED ---');
    console.log('Body:', req.body);
    try {
        const { email, uniqueCode } = req.body;

        if (!email || !uniqueCode) {
            console.log('Missing fields');
            return res.status(400).json({ success: false, message: 'Email and Unique Code are required' });
        }

        console.log('Querying DB for:', email, uniqueCode);
        const student = await Student.findOne({ email, uniqueCode });
        console.log('DB result:', student ? 'Found' : 'Not Found');

        if (!student) {
            return res.status(401).json({ success: false, message: 'Invalid Email or Unique Code' });
        }

        const payload = {
            success: true,
            student: {
                name: student.name,
                teamName: student.teamName,
                studentId: student.studentId,
                paymentSubmitted: student.paymentSubmitted,
                email: student.email,
                uniqueCode: student.uniqueCode
            }
        };
        console.log('Sending payload:', payload);
        res.json(payload);

    } catch (error) {
        console.log('--- ERROR IN VERIFY ---');
        console.log(error);
        console.error('Verify error stack:', error.stack);
        res.status(500).json({ success: false, message: 'Server error during verification' });
    }
});

// @route POST /api/submit-payment
// @desc Submit payment details and screenshot
router.post('/submit-payment', upload.single('screenshot'), async (req, res) => {
    try {
        const { email, uniqueCode, utr } = req.body;

        if (!email || !uniqueCode || !utr) {
            return res.status(400).json({ success: false, message: 'Missing required fields' });
        }

        // Verify student again
        const student = await Student.findOne({ email, uniqueCode });

        if (!student) {
            return res.status(401).json({ success: false, message: 'Unauthorized student' });
        }

        // Check if payment already submitted to prevent duplicate
        if (student.paymentSubmitted) {
            return res.status(400).json({ success: false, message: 'Payment already submitted' });
        }

        // Ensure image was uploaded
        if (!req.file) {
            return res.status(400).json({ success: false, message: 'Screenshot is required' });
        }

        // The image URL generated by Cloudinary
        const screenshotUrl = req.file.path;

        // Update student record
        student.utrCode = utr;
        student.screenshotUrl = screenshotUrl;
        student.paymentSubmitted = true;

        await student.save();

        res.json({
            success: true,
            message: 'Payment successfully recorded',
        });

    } catch (error) {
        console.error('Submit payment error:', error);
        res.status(500).json({ success: false, message: 'Server error during payment submission' });
    }
});

// @route GET /api/students
// @desc Get all students (Admin Only later)
router.get('/students', async (req, res) => {
    try {
        const students = await Student.find({}, '-__v');
        res.json({ success: true, students });
    } catch (error) {
        res.status(500).json({ success: false, message: 'Server error' });
    }
});

// ==================== HOST ROUTES ====================

// @route POST /api/host-login
// @desc Authenticate host with hardcoded credentials
router.post('/host-login', (req, res) => {
    try {
        const { email, password } = req.body;

        if (!email || !password) {
            return res.status(400).json({ success: false, message: 'Email and password are required' });
        }

        const hostEmail = process.env.HOST_EMAIL;
        const hostPassword = process.env.HOST_PASSWORD;

        if (email === hostEmail && password === hostPassword) {
            return res.json({
                success: true,
                message: 'Host authenticated successfully',
                host: { email: hostEmail }
            });
        }

        return res.status(401).json({ success: false, message: 'Invalid host credentials' });
    } catch (error) {
        console.error('Host login error:', error);
        res.status(500).json({ success: false, message: 'Server error during host login' });
    }
});

// @route GET /api/host/students
// @desc Get all students sorted by approval status (pending first, then verified, then rejected)
router.get('/host/students', async (req, res) => {
    try {
        const students = await Student.find({}, '-__v').lean();

        // Custom sort: pending → verified → rejected
        const statusOrder = { pending: 0, verified: 1, rejected: 2 };
        students.sort((a, b) => {
            const orderA = statusOrder[a.isApproved] ?? 3;
            const orderB = statusOrder[b.isApproved] ?? 3;
            if (orderA !== orderB) return orderA - orderB;
            // Secondary sort by newest first
            return new Date(b.createdAt) - new Date(a.createdAt);
        });

        res.json({ success: true, students });
    } catch (error) {
        console.error('Host students error:', error);
        res.status(500).json({ success: false, message: 'Server error' });
    }
});

// @route PUT /api/host/student/:id/status
// @desc Update student isApproved status
router.put('/host/student/:id/status', async (req, res) => {
    try {
        const { id } = req.params;
        const { status } = req.body;

        if (!['pending', 'verified', 'rejected'].includes(status)) {
            return res.status(400).json({ success: false, message: 'Invalid status. Must be pending, verified, or rejected.' });
        }

        const student = await Student.findByIdAndUpdate(
            id,
            { isApproved: status },
            { new: true }
        );

        if (!student) {
            return res.status(404).json({ success: false, message: 'Student not found' });
        }

        res.json({ success: true, message: `Student status updated to ${status}`, student });
    } catch (error) {
        console.error('Update status error:', error);
        res.status(500).json({ success: false, message: 'Server error' });
    }
});

// ==================== ATTENDANCE ROUTES ====================

const Team = require('../models/Team');

// @route GET /api/host/teams
// @desc Get all teams sorted by serialNumber
router.get('/host/teams', async (req, res) => {
    try {
        const teams = await Team.find({}).sort({ serialNumber: 1 }).lean();
        res.json({ success: true, teams });
    } catch (error) {
        console.error('Fetch teams error:', error);
        res.status(500).json({ success: false, message: 'Server error fetching teams' });
    }
});

// @route GET /api/host/teams/stats
// @desc Get attendance summary stats
router.get('/host/teams/stats', async (req, res) => {
    try {
        const teams = await Team.find({}).lean();
        const totalTeams = teams.length;
        let totalMembers = 0;
        let presentCount = 0;

        teams.forEach((team) => {
            team.members.forEach((member) => {
                totalMembers++;
                if (member.isPresent) presentCount++;
            });
        });

        res.json({
            success: true,
            stats: {
                totalTeams,
                totalMembers,
                present: presentCount,
                absent: totalMembers - presentCount,
            },
        });
    } catch (error) {
        console.error('Attendance stats error:', error);
        res.status(500).json({ success: false, message: 'Server error fetching stats' });
    }
});

// @route PUT /api/host/team/:teamId/member/:memberIndex/attendance
// @desc Toggle a member's isPresent status
router.put('/host/team/:teamId/member/:memberIndex/attendance', async (req, res) => {
    try {
        const { teamId, memberIndex } = req.params;
        const { isPresent } = req.body;

        if (typeof isPresent !== 'boolean') {
            return res.status(400).json({ success: false, message: 'isPresent must be a boolean' });
        }

        const idx = parseInt(memberIndex, 10);
        const team = await Team.findById(teamId);

        if (!team) {
            return res.status(404).json({ success: false, message: 'Team not found' });
        }

        if (idx < 0 || idx >= team.members.length) {
            return res.status(400).json({ success: false, message: 'Invalid member index' });
        }

        team.members[idx].isPresent = isPresent;
        await team.save();

        res.json({
            success: true,
            message: `${team.members[idx].name} marked as ${isPresent ? 'present' : 'absent'}`,
            team,
        });
    } catch (error) {
        console.error('Update attendance error:', error);
        res.status(500).json({ success: false, message: 'Server error updating attendance' });
    }
});

module.exports = router;
